### ISSUE TITLE
TypeError: __inc__() takes 3 positional arguments but 4 were given 

### ISSUE THREAD

**Issue by crazysal** [rusty1s/deep-graph-matching-consensus#16]
Context : 
```

Traceback (most recent call last):
  File "pascal.py", line 116, in <module>
    loss = train()
  File "pascal.py", line 73, in train
    for data in train_loader:
  File "/home/sahmed9/anaconda3/envs/pop/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/home/sahmed9/anaconda3/envs/pop/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 557, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/sahmed9/anaconda3/envs/pop/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/home/sahmed9/anaconda3/envs/pop/lib/python3.8/site-packages/torch_geometric/loader/dataloader.py", line 39, in __call__
    return self.collate(batch)
  File "/home/sahmed9/anaconda3/envs/pop/lib/python3.8/site-packages/torch_geometric/loader/dataloader.py", line 19, in collate
    return Batch.from_data_list(batch, self.follow_batch,
  File "/home/sahmed9/anaconda3/envs/pop/lib/python3.8/site-packages/torch_geometric/data/batch.py", line 63, in from_data_list
    batch, slice_dict, inc_dict = collate(
  File "/home/sahmed9/anaconda3/envs/pop/lib/python3.8/site-packages/torch_geometric/data/collate.py", line 76, in collate
    value, slices, incs = _collate(attr, values, data_list, stores,
  File "/home/sahmed9/anaconda3/envs/pop/lib/python3.8/site-packages/torch_geometric/data/collate.py", line 142, in _collate
    incs = get_incs(key, values, data_list, stores)
  File "/home/sahmed9/anaconda3/envs/pop/lib/python3.8/site-packages/torch_geometric/data/collate.py", line 187, in get_incs
    repeats = [
  File "/home/sahmed9/anaconda3/envs/pop/lib/python3.8/site-packages/torch_geometric/data/collate.py", line 188, in <listcomp>
    data.__inc__(key, value, store)
TypeError: __inc__() takes 3 positional arguments but 4 were given

```

**Comment by rusty1s** [comment]
This should be already fixed in master, see [here](https://github.com/rusty1s/deep-graph-matching-consensus/commit/cb99870b11755ce610ec8dcd6275f3f1d342f894). Updating the repo should resolve this issue.

**Comment by crazysal** [comment]
nope, doesn't solve it. 

The code-base was running a few days back, till I updated the nvidia-driver and installed the env again, I noticed your commit says pyg2.0 support. 

Can I install the previous version of pyg somehow, with which this was released till all such bugs are resolved ?

**Comment by crazysal** [comment]
my bad, forgot to re-install. 
woking now. 
Thank you !
